spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cart?serverTimezone=Asia/Seoul
    username: zerobase
    password: zerobase
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher

springdoc:
  show-login-endpoint: true
